# This is the default default default config file for ledgerweb
#
# 1. flask
hostip: 0.0.0.0
hostport: 5000

# ledgerfile
ledgerfile: /data/finance.ledger

# 3. ledger
currency: EUR
favs:
- name: EDEKA
  from: Assets:Checking
  to: Expenses:Food
- name: Rewe
  from: Assets:Checking
  to: Expenses:Food
- name: Alnatura
  from: Assets:Checking
  to: Expenses:Food
