from flask import Flask, render_template, request, redirect, url_for
import subprocess
import os.path
import yaml
import time
import fileinput

if os.path.exists('config.yaml'):
    configfile = 'config.yaml'
else:
    configfile = 'defaultconfig.yaml'

with open(configfile, 'r') as f:
    try:
        config = yaml.safe_load(f)
    except yaml.YAMLError as exc:
        print(exc)

app = Flask(__name__)
app.static_folder = 'static'

@app.route('/')
def index():
    fa = []
    for f in config['favs']:
        fa.append(f['name'])

    return render_template('index.html', favs=fa)

@app.route('/submit', methods = ['GET'])
def fsubmit():
    amount = request.args.get('amount')
    rep = request.args.get('select')
    
    fav = [x for x in config['favs'] if x['name'] == rep][0]
    
    ledgerfile = open(config['ledgerfile'], 'a')
    ledgerfile.write("{date} {rep}\n".format(date=time.strftime("%Y/%m/%d"), rep=rep))
    ledgerfile.write("    ; generated by ledgerweb\n")
    ledgerfile.write("    {f}\n".format(f=fav['from']))
    ledgerfile.write("    {to}   {amount} EUR\n\n".format(to=fav['to'], amount=amount))
    ledgerfile.close()

    return redirect(url_for('index'))

if __name__ == '__main__':
    app.run(debug=False, host=config['hostip'], port=config['hostport'])
